name: Provision K8 clusters in Datacenter
on:
  push:
jobs:
  Terraform-Kubespray:
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout
    #   uses: actions/checkout@v3
    #   with:
    #     persist-credentials: false
    #     fetch-depth: 0
    #     path: terraform
    # - name: Checkout Kubespray
    #   uses: actions/checkout@v3
    #   with:
    #     repository: kubernetes-sigs/kubespray
    #     path: kubespray
    #     persist-credentials: false
    #     fetch-depth: 0
    - name: Create host file
      run: |
        mkdir ansible;
        echo '
        ---
        - name: "Playing with Ansible and Git"
          hosts: localhost
          connection: local 
          tasks:
          - name: "just execute a ls -lrt command"
            ansible.builtin.shell:
              cmd: ls -lrt
            register: "output"

          - debug: var=output.stdout_lines
        ' > ansible/ansible-playbook.yaml
        cat ansible-playbook.yaml
    - name: Verifying files
      run: |
        ls -lrt ansible/
     #   ls -lrt terraform/
     #   ls -lrt kubespray/
    - name: Run ansible-lint
      uses: ansible-community/ansible-lint-action@v6.0.2
      with: 
        args: "ansible/ansible-playbook.yaml"

 
        
    # - name: Setup Terrafrom
    #   uses: hashicorp/setup-terraform@v1
    # - name: Terraform Format
    #   id: fmt
    #   run: terraform fmt -check
    # - name: Terraform Init
    #   id: init
    #   run: terraform init
    # - name: Terraform Validate
    #   id: validate
    #   run: terraform validate -no-color
    # - name: Terraform Plan
    #   id: plan
    #   run: terraform plan -no-color -input=false
    #   continue-on-error: true
    # - name: Terraform Plan Status
    #   if: steps.plan.outcome == 'failure'
    #   run: exit 1
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve -input=false